version: '3.8'

services:
  backend:
    build: ./backend
    container_name: paystream-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://web3.iitmandi.co.in:8351}
      ORACLE_PRIVATE_KEY: ${ORACLE_PRIVATE_KEY}
    ports:
      - "8352:5000"
    networks:
      - paystream-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}
        VITE_ORACLE_PRIVATE_KEY: ${ORACLE_PRIVATE_KEY}
        VITE_ADMIN_ADDRESS: ${VITE_ADMIN_ADDRESS:-0x95e38e215CDe9655f6cF5E89E89d00e0BB62144a}
        VITE_TREASURY_CONTRACT: ${VITE_TREASURY_CONTRACT}
        VITE_STREAM_CONTRACT: ${VITE_STREAM_CONTRACT}
        VITE_OFFRAMP_CONTRACT: ${VITE_OFFRAMP_CONTRACT}
    container_name: paystream-frontend
    restart: unless-stopped
    ports:
      - "8351:80"
    depends_on:
      - backend
    networks:
      - paystream-network

networks:
  paystream-network:
    driver: bridge
